export const penalties = [
  "Run 1 mile",
  "100 situps non-stop",
  "5 minute wall sit",
  "Jump rope for 2 minutes, double unders, can't mess up",
  "30 pushups, 1 handed",
  "20 reps squat bar, with 5 pounds more than your max",
  "50 burpees as fast as possible",
  "Hold a plank for 4 minutes",
  "200 jumping jacks without stopping",
  "40 walking lunges per leg",
  "Run stairs for 10 minutes",
  "100 mountain climbers each leg",
  "3 minute hollow body hold",
  "1 minute handstand hold (wall allowed)",
  "50 decline pushups",
  "75 air squats, deep",
  "2 mile bike sprint (or 10 min hard bike)",
  "Row 1000 meters at max effort",
  "Bear crawl 50 yards without knees touching",
  "Crab walk 50 yards",
  "60 second sprint, 60 second jog x5",
  "Hold a squat at parallel for 3 minutes",
  "50 box jumps",
  "100 calf raises slow and controlled",
  "20 pistol squats total (assist allowed)",
  "5 sets of 10 diamond pushups",
  "5 sets of 10 wide pushups",
  "100 bicycle crunches",
  "50 V-ups",
  "30 pullups (band allowed, no kipping)",
  "1 minute pullup bar hang, dead hang",
  "200 meter sprint x5",
  "10 minute jog, no walking",
  "50 kettlebell swings (moderate weight)",
  "30 goblet squats (moderate-heavy)",
  "100 banded rows",
  "50 tricep dips",
  "100 flutter kicks",
  "30 seconds sprint in place x10 (10 sec rest)",
  "10 Turkish get-ups total (light-moderate)",
  "Farmer carry 2 heavy things for 2 minutes",
  "50 reverse lunges each leg",
  "20 jump squats x3 sets",
  "15 minutes zone-2 cardio (no phone)",
  "100 Russian twists (each side counts)",
  "5 minute continuous jump rope (no tripping)",
  "500m swim (or 5 min treading water)",
  "20 minute yoga flow (no skipping poses)",
  "20 burpees every minute for 5 minutes",
  "Hold a side plank 2 minutes each side",
  "50 supermans with pause at top",
  "30 seconds wall sit + 10 squats x10 rounds",
  "100 high knees each leg",
  "5 rounds: 10 pushups + 10 situps + 10 squats",
  "Run 400m x3 with 1 min rest",
  "Hold a lunge (each leg) for 2 minutes",
  "40 inchworms",
  "100 toe touches",
  "30 minutes no-sit rule (must stand/move)",
  "50 slow perfect pushups (5-sec down)",
  "10 minutes shadowboxing nonstop",
];
